TuringLang/Libtask.jl

src/Libtask.jl
src/tarray.jl
test/tarray.jl
test/tarray2.jl

This contains updates for the TArray type and related functions.
Highlights:
- Implements indexing interface
- Implements Iterators
- Added `similar` functions
- `TArray` is now a subtype of `AbstractArray`
- Added `display` function and a new field on the `TArray` which stores the original task to aid in printing
The `TRef` type which stores arbitrary content is outside of this request for now. I'm not quite happy yet with the implementation for the moment.
Please take a look and let me know if there's anything I've missed or additional features I can tack on here.

TArray Updates

---

src/tarray.jl

Regarding discussion in #3. I've only added a warning, because I think this functionality is good for REPL users to have. `show` and `println` work as intended by printing only the current task's storage.

Added warning to display(::TArray).

---

src/Libtask.jl
src/tref.jl
test/tref.jl

This is an updated request from #10, which adds dictionary support, miscellaneous testing, and some general tidying. It was easier to start a new branch on the TuringLang organization than rebase when the actual code added is quite small.

TRefs for arbitrary storage

---

README.md
src/Libtask.jl
src/taskcopy.jl
test/brokentask.jl
test/clonetask.jl
test/runtests.jl
test/tarray.jl
test/tref.jl

To fix https://github.com/TuringLang/Libtask.jl/issues/7.

Catch task exception

---

.github/workflows/BuildDylib.yaml
README.md
deps/gh-auto-tag

#53
When version number in `Project.toml` is updated, a tag will be made according to the new version.
But we can't upload artifacts to a tag, we can only upload artifacts to a release. So now the process is:
1. someone updates the version number in `Project.toml` then commit the change
2. the push event triggers GH action, a new tag will be made on that commit
3. TagBot creates a new release on the new tag
4. GH action is triggered by the release event, then builds and uploads the artifacts

Auto tag when Project.toml updated

---

.github/workflows/Testing.yaml
Project.toml
deps/build.jl
src/Libtask.jl

This PR addresses https://github.com/TuringLang/Libtask.jl/issues/55.
I'm not sure if that's the best way to solve it but it avoids calling `Pkg.build("Libtask")` which apparently fails in CI tests. Moreover, it fixes the typo due to which, as far as I can see, the package was rebuilt each time it was loaded.

Provide error message instead of building Libtask

---

.github/workflows/Testing.yaml
Project.toml
src/tarray.jl
test/tarray.jl

This PR fixes the constructors of `TArray`, as explained in https://github.com/TuringLang/Libtask.jl/issues/74#issuecomment-706680984.

Fix constructors

---

Project.toml

This PR fixes the version number. Strangely, it seems Libtask 0.4.2 was not released.

Correct version number

---

src/ctask.jl

Not ready to merge until https://github.com/JuliaPackaging/Yggdrasil/pull/2176 is merged.

make Libtask compatible with Julia 1.6

---

src/tapedfunction.jl
src/tapedtask.jl

This PR backports the robust `produce` mechanism from #100 (leaving out `InstructionTape`). During debugging https://github.com/TuringLang/Turing.jl/pull/1757, I found some issues with the `InstructionTape`. Addressing these issues might take more time and is not necessary for now. With this PR and the new model evaluation API (https://github.com/TuringLang/Turing.jl/pull/1757), we can switch Turing to use the new `Libtask`  without `InstructionTape`.

Backport some features from #100

---

src/tapedfunction.jl
src/tapedtask.jl

Besides adding `TapeInstruction`, I did a little code refactor in https://github.com/TuringLang/Libtask.jl/pull/100, and I'd like to move that refactor onto master branch before doing benchmark and performance optimization.

backport basic refactor from PR#100

---

.github/workflows/IntegrationTest.yml

This way, the tests are actually executed instead of skipped in the `try catch` block due to incompatible versions. But, I also understand now that it's hard to do integration tests when changes need to be made at two repositories. Anyway, adding the integration tests here is nice because it's now easier to see what needs to be done and for the reviewer to see what the current status is.

Add refs to integration tests

---

Project.toml
src/tapedfunction.jl

See https://github.com/TuringLang/AdvancedPS.jl/pull/42.

Track GlobalRef

---

.github/workflows/BenchmarksAndMicroIntegration.yml
.github/workflows/IntegrationTest.yml
Project.toml
perf/p0.jl
perf/p2.jl
src/tapedfunction.jl
src/tapedtask.jl
test/ctask.jl
test/tarray.jl
test/tf.jl

Implement https://github.com/TuringLang/Libtask.jl/issues/96.

Control flow support

---

Project.toml
src/tapedfunction.jl

Benchmarked on Turing.jl/test/stdlib/RandomMeasures.jl
```
julia> @benchmark run_chain() # eval (before PR)
BenchmarkTools.Trial: 1 sample with 1 evaluation.
Single result which took 15.231 s (1.52% GC) to evaluate,
with a memory estimate of 679.26 MiB, over 9452913 allocations.
julia> @benchmark run_chain() # splatnew (after PR)
BenchmarkTools.Trial: 1 sample with 1 evaluation.
Single result which took 14.665 s (1.55% GC) to evaluate,
with a memory estimate of 655.23 MiB, over 8972863 allocations.
julia> @benchmark run_chain() # eval (before PR)
BenchmarkTools.Trial: 1 sample with 1 evaluation.
Single result which took 16.465 s (1.41% GC) to evaluate,
with a memory estimate of 679.21 MiB, over 9452903 allocations.
julia> @benchmark run_chain() # splatnew (after PR)
BenchmarkTools.Trial: …
```

Replace `eval` by generated function

---

src/tapedtask.jl

I'm still working a bit through the code in order to find performance gains. This PR applies an extract method refactoring to make the `TapedTask` easier to read. It has no negative nor positive impact on performance. I've verified this by putting a `@show` on the `TapedTask(tf, args...)` call and that shows `(32 allocations: 2.312 KiB)` in both versions. 
Because the git diff is very unhelpful, here are the before and after:
```julia
function TapedTask(tf::TapedFunction, args...)
produce_ch = Channel()
consume_ch = Channel{Int}()
task = @task try
producer = () -> begin
ttask = current_task().storage[:tapedtask]
if length(ttask.produced_val) > 0
val = pop!(ttask.produced_val)
put!(ttask.produce_ch, val)
take!(ttask.consume_ch) # wait for next consumer
end
end
tf(args...; …
```

Extract TapedTask try-catch method

---

Project.toml
README.md
perf/p0.jl
perf/p2.jl
src/Libtask.jl
src/tapedtask.jl
test/benchmarks.jl
test/runtests.jl
test/tapedtask.jl
test/tarray.jl
test/tref.jl

Dropping `CTask` fully in response to https://github.com/TuringLang/Libtask.jl/pull/121#issuecomment-1046114428. `CTask` is the name of the old implementation. The new name is `TapedTask`. Also, this PR changes the type from `TapedTask` to `TapedTask{F}`.
This PR is related to
- https://github.com/TuringLang/Turing.jl/pull/1778
- https://github.com/TuringLang/AdvancedPS.jl/pull/43
I'll be doing some performance tests before marking this PR ready for review.

Remove CTask

---

.github/workflows/Testing.yaml
Project.toml
src/Libtask.jl
src/tapedfunction.jl

Fix https://github.com/TuringLang/Libtask.jl/issues/117

Switch from IRTools to CodeInfo

---

src/tapedfunction.jl
src/tapedtask.jl

I noticed a subtle bug while investigating the performance benchmarks in #133. It turns out that we never run the taped function in `@btime` (more precisely, `tf` is only run once) because the `tf.counter` variable is not reset after each run. 
Benchmark results for this PR: 
```julia
benchmarking rosenbrock...
Run Original Function:  390.527 μs (16 allocations: 6.10 MiB)
Run TapedFunction:  479.145 μs (282 allocations: 6.11 MiB)
Run TapedFunction (compiled):  497.135 μs (309 allocations: 6.11 MiB)
benchmarking ackley...
Run Original Function:  1.396 ms (0 allocations: 0 bytes)
Run TapedFunction:  770.484 ms (16698219 allocations: 445.53 MiB)
Run TapedFunction (compiled):  743.913 ms (18498246 allocations: 592.02 MiB)
benchmarking matrix_test...
Run Original Function:  95.125 μs (16 …
```

Bugfix in running TapedFunction.

---

src/tapedfunction.jl
src/tapedtask.jl
test/tapedtask.jl

In `AdvancedPS` we often need to mutate the input of the the `TapedFunction` to handle random streams. It would be great if we could do something like:
```julia
function (model::Model) (rng::Random.AbstractRNG)
...
end
rng1 = Random.MersenneTwister()
task = Litbtask.TapedTask(model, rng1)
Libtask.consume(task)
new_rng = Random.MersenneTwister()
task2 = Libtask.copy(task, new_rng)
Libtask.consume(task) # Generates random numbers from rng1
Libtask.consume(task2) # Generates random numbers from new_rng
```
but for this to work we need to update the `args...` and ` bindings` appropriately when we `copy` the running task. 
This is just a draft, I'm not sure about all the implications of this change, especially with #138

Update args at copy

---

Project.toml
perf/benchmark.jl
src/Libtask.jl
src/tapedfunction.jl
src/tapedtask.jl

The first try is using generated function to run instruction.

Peformance Optimization

---

src/tapedfunction.jl
src/tapedtask.jl
test/tapedtask.jl

Bugfix on dealing with args

---

Project.toml
src/tapedfunction.jl
src/tapedtask.jl
test/tapedtask.jl

New construction for TapedTask

---

Project.toml
src/tapedfunction.jl
test/issues.jl

Fix https://github.com/TuringLang/Turing.jl/issues/1873

Translate new construction of NamedTuple

---

Project.toml
src/tapedtask.jl
test/tape_copy.jl

Not sure it's an issue but seems a bit weird to override the `deepcopy_types` from what the user provides. 
On `master` this produces the wrong result because `Ref` and `Array` are not deepcopied anymore
```julia
using Libtask
struct DummyType end
function f(start::Int)
t = [start]
while true
produce(t[1])
t[1] = 1 + t[1]
end
end
ttask = TapedTask(f, 0; deepcopy_types=DummyType)
println(consume(ttask)) # 0 Correct 
ttask2 = copy(ttask)
println(consume(ttask2)) # 1 Correct
println(consume(ttask)) # 2 Incorrect
println(consume(ttask2)) # 3 Incorrect
```
Maybe we can assume that `Array` and `Ref` would always be deepcopied unless explicitly overloaded in `tape_deepcopy` ?

Union types

---

.github/workflows/Testing.yaml
Project.toml
perf/benchmark.jl
src/Libtask.jl
src/tapedfunction.jl
test/issues.jl

Fix https://github.com/TuringLang/Libtask.jl/issues/174

static_parameter expr

---

perf/benchmark.jl

Fixed some minor issues in benchmarks. It now runs but produces the error below
```julia
julia> benchmark_driver!(rosenbrock, x)
####################################################################
benchmarking rosenbrock...
ERROR: Unhandled stmt $(Expr(:loopinfo, Symbol("julia.simdloop"), nothing)) of type Expr
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] (::Libtask.var"#14#26"{…})(::Tuple{…})
@ Libtask ~/.julia/packages/Libtask/Aw9k4/src/copyable_task.jl:708
[3] iterate
@ ./generator.jl:48 [inlined]
[4] collect(itr::Base.Generator{Base.Iterators.Enumerate{…}, Libtask.var"#14#26"{…}})
@ Base ./array.jl:791
[5] map
@ ./abstractarray.jl:3399 [inlined]
[6] (::Libtask.var"#13#25"{…})(::Tuple{…})
@ Libtask ~/.julia/packages/Libtask/Aw9k4/src/copyable_task.jl:552
[7] iterate
@ …
```

Fix benchmarks 

---

Project.toml
src/copyable_task.jl
test/copyable_task.jl

This fixes #185, and adds a helpful error message if one tries to call `TapedTask(_, produce, x)` (which I suspect we can't make work for somewhat deep reasons).
The problem in #185 is that sometimes the IR has `:invoke` expressions where the thing being invoked isn't literally `produce`, but rather a IR/BB ID referencing a variable that is `produce`. In these cases `is_produce_stmt` fails to recognise that this is indeed a call to produce. At least in the cases that my MWE brings up, however, the `:invoke` still carries with it the knowledge that this is `MethodInstance` of `produce`, so I changed the check to look for that.
I don't know what I'm doing when I'm messing with things like `MethodInstance`s, so would be very good to get @willtebbutt's eyes on this. Maybe there's a more …

Issue #185

---

docs/src/internals.md
src/copyable_task.jl
src/test_utils.jl

Another case where I'm changing things that I only have a superficial understanding of. @willtebbutt, could you please check that `check_varargs` makes sense to you, and feel free to propose a better solution.
All the tests added here fail on main.
Closes #186

Fix varargs calls

---

Project.toml
src/copyable_task.jl
test/copyable_task.jl

We had a bug where the return value of a `produce` call was not being written into the refs, and thus if it was used in some way we hit an `UndefRefError: access to undefined reference`. This fixes that, and adds a test that used to fail.
Fixes the immediate issue with #190, but does not close it, because the same MWE in that issue has another problem.

Fix using return value of produce
